/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ActorDefs from '../../../app/bsky/actor/defs.defs.js'
import * as LabelDefs from '../../../com/atproto/label/defs.defs.js'

const $nsid = 'chat.bsky.actor.defs'

export { $nsid }

type MemberRole = 'owner' | 'standard' | l.UnknownString

export type { MemberRole }

const memberRole = l.string<{ knownValues: ['owner', 'standard'] }>()

export { memberRole }

type ProfileViewBasic = {
  $type?: 'chat.bsky.actor.defs#profileViewBasic'
  did: l.DidString
  handle: l.HandleString
  displayName?: string
  avatar?: l.UriString
  associated?: ActorDefs.ProfileAssociated
  viewer?: ActorDefs.ViewerState
  labels?: LabelDefs.Label[]
  createdAt?: l.DatetimeString

  /**
   * Set to true when the actor cannot actively participate in conversations
   */
  chatDisabled?: boolean
  verification?: ActorDefs.VerificationState

  /**
   * Union field that has data specific to different kinds of convos.
   */
  kind?:
    | l.$Typed<DirectConvoMember>
    | l.$Typed<GroupConvoMember>
    | l.Unknown$TypedObject
}

export type { ProfileViewBasic }

const profileViewBasic = l.typedObject<ProfileViewBasic>(
  $nsid,
  'profileViewBasic',
  l.object({
    did: l.string({ format: 'did' }),
    handle: l.string({ format: 'handle' }),
    displayName: l.optional(l.string({ maxGraphemes: 64, maxLength: 640 })),
    avatar: l.optional(l.string({ format: 'uri' })),
    associated: l.optional(
      l.ref<ActorDefs.ProfileAssociated>(
        (() => ActorDefs.profileAssociated) as any,
      ),
    ),
    viewer: l.optional(
      l.ref<ActorDefs.ViewerState>((() => ActorDefs.viewerState) as any),
    ),
    labels: l.optional(
      l.array(l.ref<LabelDefs.Label>((() => LabelDefs.label) as any)),
    ),
    createdAt: l.optional(l.string({ format: 'datetime' })),
    chatDisabled: l.optional(l.boolean()),
    verification: l.optional(
      l.ref<ActorDefs.VerificationState>(
        (() => ActorDefs.verificationState) as any,
      ),
    ),
    kind: l.optional(
      l.typedUnion(
        [
          l.typedRef<DirectConvoMember>((() => directConvoMember) as any),
          l.typedRef<GroupConvoMember>((() => groupConvoMember) as any),
        ],
        false,
      ),
    ),
  }),
)

export { profileViewBasic }

/** [NOTE: This is under active development and should be considered unstable while this note is here]. */
type DirectConvoMember = { $type?: 'chat.bsky.actor.defs#directConvoMember' }

export type { DirectConvoMember }

/** [NOTE: This is under active development and should be considered unstable while this note is here]. */
const directConvoMember = l.typedObject<DirectConvoMember>(
  $nsid,
  'directConvoMember',
  l.object({}),
)

export { directConvoMember }

/** [NOTE: This is under active development and should be considered unstable while this note is here]. */
type GroupConvoMember = {
  $type?: 'chat.bsky.actor.defs#groupConvoMember'

  /**
   * Who added this member. Only present if the member was added (instead of joining via link).
   */
  addedBy?: ProfileViewBasic

  /**
   * The member's role within this conversation. Only present in group conversation member lists.
   */
  role: MemberRole
}

export type { GroupConvoMember }

/** [NOTE: This is under active development and should be considered unstable while this note is here]. */
const groupConvoMember = l.typedObject<GroupConvoMember>(
  $nsid,
  'groupConvoMember',
  l.object({
    addedBy: l.optional(
      l.ref<ProfileViewBasic>((() => profileViewBasic) as any),
    ),
    role: l.ref<MemberRole>((() => memberRole) as any),
  }),
)

export { groupConvoMember }
