/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'chat.bsky.moderation.subscribeModEvents'

export { $nsid }

/** Subscribe to stream of chat events targeted to moderation. Private endpoint. */
const main = l.subscription(
  $nsid,
  l.params({ cursor: l.optional(l.string()) }),
  l.typedUnion(
    [l.typedRef<EventConvoFirstMessage>((() => eventConvoFirstMessage) as any)],
    false,
  ),
  ['FutureCursor', 'ConsumerTooSlow'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Message = l.InferSubscriptionMessage<typeof main>

export const $lxm = main.nsid,
  $params = main.parameters,
  $message = main.message

type EventConvoFirstMessage = {
  $type?: 'chat.bsky.moderation.subscribeModEvents#eventConvoFirstMessage'
  convoId: string
  createdAt: l.DatetimeString
  messageId?: string

  /**
   * The list of DIDs message recipients. Does not include the sender, which is in the `user` field
   */
  recipients: l.DidString[]
  rev: string

  /**
   * The DID of the message author.
   */
  user: l.DidString
}

export type { EventConvoFirstMessage }

const eventConvoFirstMessage = l.typedObject<EventConvoFirstMessage>(
  $nsid,
  'eventConvoFirstMessage',
  l.object({
    convoId: l.string(),
    createdAt: l.string({ format: 'datetime' }),
    messageId: l.optional(l.string()),
    recipients: l.array(l.string({ format: 'did' })),
    rev: l.string(),
    user: l.string({ format: 'did' }),
  }),
)

export { eventConvoFirstMessage }
