/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ActorDefs from '../actor/defs.defs.js'

const $nsid = 'chat.bsky.group.defs'

export { $nsid }

type LinkEnabledStatus = 'enabled' | 'disabled' | l.UnknownString

export type { LinkEnabledStatus }

const linkEnabledStatus = l.string<{ knownValues: ['enabled', 'disabled'] }>()

export { linkEnabledStatus }

type JoinRule = 'anyone' | 'followedByOwner' | l.UnknownString

export type { JoinRule }

const joinRule = l.string<{ knownValues: ['anyone', 'followedByOwner'] }>()

export { joinRule }

type JoinLinkView = {
  $type?: 'chat.bsky.group.defs#joinLinkView'
  code: string
  enabledStatus: LinkEnabledStatus
  requireApproval: boolean
  joinRule: JoinRule
  createdAt: l.DatetimeString
}

export type { JoinLinkView }

const joinLinkView = l.typedObject<JoinLinkView>(
  $nsid,
  'joinLinkView',
  l.object({
    code: l.string(),
    enabledStatus: l.ref<LinkEnabledStatus>((() => linkEnabledStatus) as any),
    requireApproval: l.boolean(),
    joinRule: l.ref<JoinRule>((() => joinRule) as any),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { joinLinkView }

type GroupPublicView = {
  $type?: 'chat.bsky.group.defs#groupPublicView'
  name: string
  owner: ActorDefs.ProfileViewBasic
  memberCount: number
  requireApproval: boolean
}

export type { GroupPublicView }

const groupPublicView = l.typedObject<GroupPublicView>(
  $nsid,
  'groupPublicView',
  l.object({
    name: l.string(),
    owner: l.ref<ActorDefs.ProfileViewBasic>(
      (() => ActorDefs.profileViewBasic) as any,
    ),
    memberCount: l.integer(),
    requireApproval: l.boolean(),
  }),
)

export { groupPublicView }

type JoinRequestView = {
  $type?: 'chat.bsky.group.defs#joinRequestView'
  convoId: string
  requestedBy: ActorDefs.ProfileViewBasic
  requestedAt: l.DatetimeString
}

export type { JoinRequestView }

const joinRequestView = l.typedObject<JoinRequestView>(
  $nsid,
  'joinRequestView',
  l.object({
    convoId: l.string(),
    requestedBy: l.ref<ActorDefs.ProfileViewBasic>(
      (() => ActorDefs.profileViewBasic) as any,
    ),
    requestedAt: l.string({ format: 'datetime' }),
  }),
)

export { joinRequestView }
