/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as GroupDefs from './defs.defs.js'

const $nsid = 'chat.bsky.group.getGroupPublicInfo'

export { $nsid }

/** [NOTE: This is under active development and should be considered unstable while this note is here]. Get public information about a group from an join link. */
const main = l.query(
  $nsid,
  l.params({ code: l.string() }),
  l.jsonPayload({
    group: l.ref<GroupDefs.GroupPublicView>(
      (() => GroupDefs.groupPublicView) as any,
    ),
  }),
  ['InvalidCode'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
