/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.putLivePresence'

export { $nsid }

/** Create, refresh, or clear the caller's live cabildeo presence. Requires auth. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    cabildeo: l.string({ format: 'at-uri' }),
    sessionId: l.string({ maxLength: 128, maxGraphemes: 128 }),
    present: l.optional(l.withDefault(l.boolean(), true)),
  }),
  l.jsonPayload({
    cabildeo: l.string({ format: 'at-uri' }),
    present: l.boolean(),
    expiresAt: l.optional(l.string({ format: 'datetime' })),
  }),
  ['NotFound', 'InvalidPhase', 'LiveStatusRequired'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
