/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.civic.vote'

export { $nsid }

/** A signed civic vote. Cabildeo option votes use selectedOption; policy consensus votes use signal from -3 to +3. */
type Main = {
  $type: 'com.para.civic.vote'

  /**
   * The proposal, policy, matter, or cabildeo record being voted on.
   */
  subject?: l.AtUriString

  /**
   * Optional semantic type for clients and indexers.
   */
  subjectType?:
    | 'cabildeo'
    | 'policy'
    | 'matter'
    | 'governance'
    | l.UnknownString
  cabildeo?: l.AtUriString
  selectedOption?: number

  /**
   * Weighted consensus signal for policy-style votes: -3 strong opposition, 0 neutral/abstain, +3 strong support.
   */
  signal?: number

  /**
   * Optional voter rationale for the signal.
   */
  reason?: string
  isDirect: boolean
  delegatedFrom?: l.DidString[]
  createdAt: l.DatetimeString
}

export type { Main }

/** A signed civic vote. Cabildeo option votes use selectedOption; policy consensus votes use signal from -3 to +3. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    subject: l.optional(l.string({ format: 'at-uri' })),
    subjectType: l.optional(
      l.string<{
        knownValues: ['cabildeo', 'policy', 'matter', 'governance']
      }>(),
    ),
    cabildeo: l.optional(l.string({ format: 'at-uri' })),
    selectedOption: l.optional(l.integer({ minimum: 0 })),
    signal: l.optional(l.integer({ minimum: -3, maximum: 3 })),
    reason: l.optional(l.string({ maxLength: 1000 })),
    isDirect: l.boolean(),
    delegatedFrom: l.optional(
      l.array(l.string({ format: 'did' }), { maxLength: 10000 }),
    ),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
