/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.community.createBoard'

export { $nsid }

/** Creates a PARA community board. Automatically instantiates the underlying general (270) and subdelegate (30) chats in the bsky chat server. Generates a founder starter pack draft. */
const main = l.procedure(
  $nsid,
  l.params(),
  l.jsonPayload({
    name: l.string({ minLength: 1, maxGraphemes: 128, maxLength: 1280 }),
    quadrant: l.string({ maxLength: 64 }),
    description: l.optional(l.string({ maxLength: 3000 })),
    founderStarterPackName: l.optional(l.string({ maxLength: 3000 })),
  }),
  l.jsonPayload({
    uri: l.string({ format: 'at-uri' }),
    cid: l.string({ format: 'cid' }),
    delegatesChatId: l.string(),
    subdelegatesChatId: l.string(),
    founderStarterPackUri: l.optional(l.string({ format: 'at-uri' })),
  }),
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Input<B = l.BinaryData> = l.InferMethodInput<typeof main, B>
export type $InputBody<B = l.BinaryData> = l.InferMethodInputBody<
  typeof main,
  B
>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $input = main.input,
  $output = main.output
