/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ConvoDefs from './defs.defs.js'
import * as ActorDefs from '../actor/defs.defs.js'

const $nsid = 'chat.bsky.convo.getMessages'

export { $nsid }

/** Returns a page of messages from a conversation. */
const main = l.query(
  $nsid,
  l.params({
    convoId: l.string(),
    limit: l.optional(
      l.withDefault(l.integer({ minimum: 1, maximum: 100 }), 50),
    ),
    cursor: l.optional(l.string()),
  }),
  l.jsonPayload({
    cursor: l.optional(l.string()),
    messages: l.array(
      l.typedUnion(
        [
          l.typedRef<ConvoDefs.MessageView>(
            (() => ConvoDefs.messageView) as any,
          ),
          l.typedRef<ConvoDefs.DeletedMessageView>(
            (() => ConvoDefs.deletedMessageView) as any,
          ),
          l.typedRef<ConvoDefs.SystemMessageView>(
            (() => ConvoDefs.systemMessageView) as any,
          ),
        ],
        false,
      ),
    ),
    relatedProfiles: l.optional(
      l.array(
        l.ref<ActorDefs.ProfileViewBasic>(
          (() => ActorDefs.profileViewBasic) as any,
        ),
      ),
    ),
  }),
  ['InvalidConvo'],
)
export { main }

export type $Params = l.InferMethodParams<typeof main>
export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>
export type $OutputBody<B = l.BinaryData> = l.InferMethodOutputBody<
  typeof main,
  B
>

export const $lxm = main.nsid,
  $params = main.parameters,
  $output = main.output
