/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.community.board'

export { $nsid }

/** A repository record acting as the anchor for a PARA community, linking the spatial map quadrant to the underlying ATProto group chats. */
type Main = {
  $type: 'com.para.community.board'
  name: string
  description?: string

  /**
   * Spatial mapping token indicating the nonant or 25th block.
   */
  quadrant: string

  /**
   * Reference to the 270-member bounded bsky group chat.
   */
  delegatesChatId: string

  /**
   * Reference to the 30-member bounded public-view bsky group chat.
   */
  subdelegatesChatId: string

  /**
   * The lifecycle status of the community.
   */
  status: 'draft' | 'active' | l.UnknownString

  /**
   * Reference to the starter pack used to track the founding member quorum.
   */
  founderStarterPackUri?: l.AtUriString
  createdAt: l.DatetimeString
}

export type { Main }

/** A repository record acting as the anchor for a PARA community, linking the spatial map quadrant to the underlying ATProto group chats. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    name: l.string({ minLength: 1, maxGraphemes: 128, maxLength: 1280 }),
    description: l.optional(l.string({ maxLength: 3000 })),
    quadrant: l.string({ maxLength: 64 }),
    delegatesChatId: l.string(),
    subdelegatesChatId: l.string(),
    status: l.string<{ knownValues: ['draft', 'active'] }>(),
    founderStarterPackUri: l.optional(l.string({ format: 'at-uri' })),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
