/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as CommunityDefs from './defs.defs.js'

const $nsid = 'com.para.community.governance'

export { $nsid }

/** A published governance record for a PARA community. This is the canonical contract for moderators, officials, deputy roles, and governance metadata exposed to clients. */
type Main = {
  $type: 'com.para.community.governance'
  community: string
  communityId?: string
  slug: string
  createdAt: l.DatetimeString
  updatedAt: l.DatetimeString
  moderators: CommunityDefs.ModeratorView[]
  officials: CommunityDefs.OfficialView[]
  deputies: CommunityDefs.DeputyRoleView[]
  metadata?: CommunityDefs.Metadata
  editHistory?: CommunityDefs.HistoryEntry[]
}

export type { Main }

/** A published governance record for a PARA community. This is the canonical contract for moderators, officials, deputy roles, and governance metadata exposed to clients. */
const main = l.record<'any', Main>(
  'any',
  $nsid,
  l.object({
    community: l.string({ maxGraphemes: 128, maxLength: 256 }),
    communityId: l.optional(l.string({ maxGraphemes: 128, maxLength: 256 })),
    slug: l.string({ maxGraphemes: 128, maxLength: 128 }),
    createdAt: l.string({ format: 'datetime' }),
    updatedAt: l.string({ format: 'datetime' }),
    moderators: l.array(
      l.ref<CommunityDefs.ModeratorView>(
        (() => CommunityDefs.moderatorView) as any,
      ),
    ),
    officials: l.array(
      l.ref<CommunityDefs.OfficialView>(
        (() => CommunityDefs.officialView) as any,
      ),
    ),
    deputies: l.array(
      l.ref<CommunityDefs.DeputyRoleView>(
        (() => CommunityDefs.deputyRoleView) as any,
      ),
    ),
    metadata: l.optional(
      l.ref<CommunityDefs.Metadata>((() => CommunityDefs.metadata) as any),
    ),
    editHistory: l.optional(
      l.array(
        l.ref<CommunityDefs.HistoryEntry>(
          (() => CommunityDefs.historyEntry) as any,
        ),
      ),
    ),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
