/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.para.community.membership'

export { $nsid }

/** Membership state of an actor in a Para community. */
type Main = {
  $type: 'com.para.community.membership'

  /**
   * Reference to the community board record.
   */
  community: l.AtUriString
  membershipState:
    | 'pending'
    | 'active'
    | 'left'
    | 'removed'
    | 'blocked'
    | l.UnknownString
  roles?: string[]
  source?: string
  joinedAt: l.DatetimeString
  leftAt?: l.DatetimeString
}

export type { Main }

/** Membership state of an actor in a Para community. */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    community: l.string({ format: 'at-uri' }),
    membershipState: l.string<{
      knownValues: ['pending', 'active', 'left', 'removed', 'blocked']
    }>(),
    roles: l.optional(
      l.array(l.string({ maxLength: 64, maxGraphemes: 64 }), { maxLength: 16 }),
    ),
    source: l.optional(l.string({ maxLength: 64, maxGraphemes: 64 })),
    joinedAt: l.string({ format: 'datetime' }),
    leftAt: l.optional(l.string({ format: 'datetime' })),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
